apiVersion: v1
kind: Service
metadata:  
  name: nodeapp-svc
spec:
  selector:    
    app: nodeapp
  type: NodePort
  ports:  
  - name: http
    port: 80
    targetPort: 8080
    nodePort: 30000
    protocol: TCP
